/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.glb --transform 
Files: scene.glb [45.74MB] > C:\Users\ProUSer\Documents\3d\New folder\1\scene-transformed.glb [560.08KB] (99%)
Author: Оrрндп ЯТG (https://sketchfab.com/orphanrtg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/komatsu-sk820-skid-steer-loader-9d16f3d8b3b0456e86db243376b2a390
Title: Komatsu SK820 Skid Steer Loader
*/

"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";


const A = React.memo(function A(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/a-transformed.glb");

  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.position.y =
      -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;
    modelRef.current.rotation.y += 0.1;
  });
  return (
    <group 
	  {...props}
      dispose={null}
      ref={modelRef}
      position={[0, -1.5, 0]}
      scale={[0.5, 0.5, 0.5]}
      rotation={[0.25, 0, 0]}
	>
      <mesh geometry={nodes.Buldo_TT_Buldo_TT_u1_v1_0.geometry} material={materials.Buldo_TT_u1_v1} rotation={[-Math.PI / 2, 0, 0]} scale={0.181} />
      <mesh geometry={nodes.Buldo_TT_Buldo_TT_u2_v1_0.geometry} material={materials.Buldo_TT_u2_v1} rotation={[-Math.PI / 2, 0, 0]} scale={0.181} />
    </group>
  );
});
export default A;
useGLTF.preload('/a-transformed.glb')
