/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf --transform 
Files: scene.gltf [5.85KB] > C:\Users\ProUSer\Documents\3d\New folder\mijnwerker (1)\scene-transformed.glb [937.56KB] (-15927%)
Author: 3dnederlandsmijnmuseum (https://sketchfab.com/3dnederlandsmijnmuseum)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mijnwerker-fd3cda870e7d4a71b10f525fa7e86335
Title: Mijnwerker
*/

"use client"
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

const C = React.memo(function C (props) {

  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/c-transformed.glb");

  const modelRef = useRef();

  useFrame((state) => {
    /*modelRef.current.position.y =
      -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;*/
    modelRef.current.rotation.y += 0.1;
  });
  return (
    <group 
    {...props} dispose={null}
      ref={modelRef}
      position={[0, -1.5, 0]}
      scale={[1, 1, 1]}
      rotation={[0.25, 0, 0]}
    >
      <mesh geometry={nodes.Object_2.geometry} material={materials.Miner} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  );
});
export default C;
useGLTF.preload('/models/c-transformed.glb')
