/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [14.37KB] > C:\Users\ProUSer\Downloads\desktop_computer\scene-transformed.glb [211.48KB] (-1372%)
Author: Tyler P Halterman (https://sketchfab.com/tylerhalterman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desktop-computer-561abc2fc95941609fc7bc6f232895c2
Title: Desktop Computer
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const DModel = React.memo(function DModel(props) {
  const { nodes, materials } = useGLTF('/models/d-transformed.glb')
  const modelRef= useRef();
  useFrame( () =>{
     modelRef.current.rotation.y+=0.1;
  });

  return (
    <group 
         {...props} 
         dispose={null}
         ref={modelRef}
         position={[0,0,0]}
         rotation={[0.25,0,0]}
         scale={ [,2,2] }
         >
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials['01___Default']} scale={0.501} />
    </group>
  );
});

export default DModel

useGLTF.preload('/models/d-transformed.glb')
