/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf --transform 
Files: scene.gltf [13.47KB] > C:\Users\ProUSer\Documents\3d\More\excavator_3d_scan_raw\scene-transformed.glb [1.85MB] (-13635%)
Author: Fovea (https://sketchfab.com/3dfovea)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/excavator-3d-scan-raw-59a1365a0eda4aeab6795fb65a37e01f
Title: Excavator 3d scan RAW
*/

"use client"
import React, { useRef} from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

const Exc = React.memo(function Exc (props) {
  const { nodes, materials } = useGLTF('/models/exc-transformed.glb')
  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.position.y =
      -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;
    modelRef.current.rotation.y += 0.1;
  });
  return (
    <group 
    {...props} dispose={null}
      ref={modelRef}
      position={[0, -1.5, 0]}
      scale={[0.1, 0.1, 0.1]}
      rotation={[0.25, 0, 0]}
    
    >
      <mesh geometry={nodes.Object_2.geometry} material={materials['200222_Excavad_RC_R0_Material_u1_v1']} position={[0, -3.708, 10.769]} rotation={[-Math.PI, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['200222_Excavad_RC_R0_Material_u1_v2']} position={[0, -3.708, 10.769]} rotation={[-Math.PI, 0, 0]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['200222_Excavad_RC_R0_Material_u2_v1']} position={[0, -3.708, 10.769]} rotation={[-Math.PI, 0, 0]} />
    </group>
  );
});

export default Exc;
useGLTF.preload('/models/exc-transformed.glb')
