/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [4.9KB] > C:\Users\ProUSer\Downloads\globe\scene-transformed.glb [367.54KB] (-7401%)
Author: Glowbox 3D (https://sketchfab.com/ra3id)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/globe-59af1994b3224c0893729fec19eb4438
Title: Globe
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const GlobeModel = React.memo(function GlobeModel(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/globe-transformed.glb");

  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  });

  return (
    <group {...props} dispose={null}
      position={[0, -1.0, 0]}
      scale={[0.06, 0.06, 0.06]}
      rotation={[0.4, -1, 0]
      }>
      <mesh 
      geometry={nodes.Cylinder__0.geometry} 
      material={materials['Scene_-_Root']} 
      rotation={[-Math.PI / 2, 0, 0]} 
      scale={100} />
    </group>
   );
  });
export default GlobeModel;
useGLTF.preload('/models/globe-transformed.glb')
