/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [3.58KB] > C:\Users\ProUSer\Downloads\simple_pen\scene-transformed.glb [51.93KB] (-1351%)
Author: Blender3D (https://sketchfab.com/Blender3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-pen-be6e3308c49841778c4de0cabf36432e
Title: Simple Pen
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const PenModel = React.memo(function PenModel(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/pen-transformed.glb");
  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.3;
  });


  return (
    <group 
    {...props} 
    dispose={null}
    scale={[0.3, 0.3, 0.3]}
    position={[0, 1, 0]}
    ref={modelRef}
    >

      <mesh 
      geometry={nodes.Object_2.geometry} 
      material={materials.None} 
      rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  );
});
export default PenModel;
useGLTF.preload('/models/pen-transformed.glb')
