/* 
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Robot = React.memo(function Robot(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/robot-transformed.glb");

  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.rotation.y+=0.1;
  });

  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      position={[0, -1.5, 0]}
      scale={[0.2, 0.2, 0.2]}
      rotation={[0.25, 0, 0]}
    >
      
      <mesh 
      geometry={nodes.Object_2.geometry} 
      material={materials['lambert1.001']} 
      rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  );
});

export default Robot;
useGLTF.preload("/models/robot-transformed.glb");

