/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [90.18KB] > C:\Users\ProUSer\Documents\3d\winter_soldier\scene-transformed.glb [7.77MB] (-8520%)
Author: Brad Groatman (https://sketchfab.com/groatman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/winter-soldier-1483f6d1866e4606b41bc23a1176d05a
Title: Winter Soldier
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const SojaModel = React.memo(function SojaModel(props) {
  const { nodes, materials } = useGLTF('/models/soja-transformed.glb')
  const modelRef= useRef();

  useFrame( () =>{
    modelRef.current.rotation.y+=0.1;
  })
  return (
    <group 
      {...props} 
      dispose={null}
      ref= { modelRef}
      position={[0,-1,0]}
      scale={[0.5,0.5,0.5,]}
      rotation={[0.25,0,0]}
      >
      <mesh geometry={nodes.head_head_0.geometry} material={materials.head} />
      <mesh geometry={nodes.eyebrows_eyebrows_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.hairBase_hairBase_0.geometry} material={materials.hairBase} />
      <mesh geometry={nodes.hairstrands2_hairstrands2_0.geometry} material={materials.hairstrands2} />
      <mesh geometry={nodes.kneepadstraps_kneepadstraps_0.geometry} material={materials.kneepadstraps} />
      <mesh geometry={nodes.torso_torso_0.geometry} material={materials.torso} />
      <mesh geometry={nodes.torsostraps_torsostraps_0.geometry} material={materials.torsostraps} />
      <mesh geometry={nodes.shldstrapconnect_shldstrapconnect_0.geometry} material={materials.shldstrapconnect} />
      <mesh geometry={nodes.belt_belt_0.geometry} material={materials.belt} />
      <mesh geometry={nodes.neck_neck_0.geometry} material={materials.neck} />
      <mesh geometry={nodes.shldstraps_shldstraps_0.geometry} material={materials.shldstraps} />
      <mesh geometry={nodes.shldstrappads_shldstrappads_0.geometry} material={materials.shldstrappads} />
      <mesh geometry={nodes.abstrap_abstrap_0.geometry} material={materials.abstrap} />
      <mesh geometry={nodes.abstrap1_abstrap1_0.geometry} material={materials.abstrap1} />
      <mesh geometry={nodes.rightarm_1_rightarm_1_0.geometry} material={materials.rightarm_1} />
      <mesh geometry={nodes.pants_pants_0.geometry} material={materials.pants} />
      <mesh geometry={nodes.holsterstrap_holsterstrap_0.geometry} material={materials.holsterstrap} />
      <mesh geometry={nodes.boots1_2_boots1_2_0.geometry} material={materials.boots1_2} />
      <mesh geometry={nodes.bootlaces_bootlaces_0.geometry} material={materials.bootlaces} />
      <mesh geometry={nodes.boottops_boottops_0.geometry} material={materials.boottops} />
      <mesh geometry={nodes.hands_hands_0.geometry} material={materials.hands} />
      <mesh geometry={nodes.kneepads_kneepads_0.geometry} material={materials.kneepads} />
      <mesh geometry={nodes.eyes_eyes_0.geometry} material={materials.eyes} />
      <mesh geometry={nodes.leftarm_leftarm_0.geometry} material={materials.leftarm} />
      <mesh geometry={nodes.gun_gun_0.geometry} material={materials.material} />
      <mesh geometry={nodes.tentacles_tentacles_0.geometry} material={materials.tentacles} />
      <mesh geometry={nodes.base_base_0.geometry} material={materials.base} />
    </group>
  );
});
export default SojaModel
useGLTF.preload('/models/soja-transformed.glb')
