/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf --transform 
Files: scene.gltf [358.64KB] > C:\Users\ProUSer\Documents\3d\More\boeing-stearman_model_75\scene-transformed.glb [1.97MB] (-450%)
Author: Stéphane Agullo (https://sketchfab.com/sa3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boeing-stearman-model-75-57035fcd89e7496aa712ca1b522700fd
Title: BOEING-STEARMAN MODEL 75
*/

"use client"
import React, { useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

const Tr = React.memo(function Tr(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/tr-transformed.glb");

  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.position.y =
      -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;
    modelRef.current.rotation.y += 0.1;
  });
  return (
    <group 
     {...props}
      dispose={null}
      ref={modelRef}
      position={[0, -1.5, 0]}
      scale={[0.005, 0.005, 0.005]}
      rotation={[0.25, 0, 0]}
    >
      <group name="Sketchfab_Scene">
        <group name="RootNode">
          <group name="avion_DEF5Layer2" position={[0, 0, -8376.507]} scale={[0.2, 0.2, 0.3]}>
            <mesh name="avion_DEF5Layer2_NUAGES_0" geometry={nodes.avion_DEF5Layer2_NUAGES_0.geometry} material={materials.NUAGES} />
          </group>
          <group name="avion_DEF5Layer3_(1)" position={[0, 0, -9023.669]} scale={[0.3, 0.4, 0.3]}>
            <mesh name="avion_DEF5Layer3_(1)_PLUIE_0" geometry={nodes['avion_DEF5Layer3_(1)_PLUIE_0'].geometry} material={materials.PLUIE} />
          </group>
          <group name="avion_DEF5Layer3_(2)" position={[0, 0, -8861.25]} rotation={[0, 0, -2.691]} scale={[0.3, 0.4, 0.3]}>
            <mesh name="avion_DEF5Layer3_(2)_PLUIE_0" geometry={nodes['avion_DEF5Layer3_(2)_PLUIE_0'].geometry} material={materials.PLUIE} />
          </group>
          <group name="avion_DEF5Layer3_(3)" position={[0, 0, -9053.272]} rotation={[0, 0, 1.166]} scale={[0.3, 0.4, 0.3]}>
            <mesh name="avion_DEF5Layer3_(3)_PLUIE_0" geometry={nodes['avion_DEF5Layer3_(3)_PLUIE_0'].geometry} material={materials.PLUIE} />
          </group>
          <group name="avion_DEF5Layer3_(4)" position={[0, 0, -8861.25]} rotation={[0, 0, -1.443]} scale={[0.3, 0.4, 0.3]}>
            <mesh name="avion_DEF5Layer3_(4)_PLUIE_0" geometry={nodes['avion_DEF5Layer3_(4)_PLUIE_0'].geometry} material={materials.PLUIE} />
          </group>
        </group>
        <group name="TOT_(1)">
          <group name="avion_DEF5corps_(1)" rotation={[-0.001, -0.001, 0]}>
            <group name="avion_DEF5elice_(1)" rotation={[0, 0, -2.095]}>
              <mesh name="avion_DEF5elice_(1)_fer_elices2_0" geometry={nodes['avion_DEF5elice_(1)_fer_elices2_0'].geometry} material={materials.fer_elices2} />
              <mesh name="avion_DEF5elice_(1)_black_0" geometry={nodes['avion_DEF5elice_(1)_black_0'].geometry} material={materials.black} />
            </group>
            <group name="avion_DEF5aileron-AR-vert_(1)">
              <mesh name="avion_DEF5aileron-AR-vert_(1)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-vert_(1)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AR-ga_(1)" position={[0, -22.96, 1.776]} rotation={[-0.048, 0, 0]}>
              <mesh name="avion_DEF5aileron-AR-ga_(1)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-ga_(1)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AR-dr_(1)" position={[0, -8.521, 0.531]} rotation={[-0.018, 0, 0]}>
              <mesh name="avion_DEF5aileron-AR-dr_(1)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-dr_(1)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-bas-ga_(1)" position={[0, 0.485, -2.965]} rotation={[-0.048, 0, 0]}>
              <mesh name="avion_DEF5aileron-AV-bas-ga_(1)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-bas-ga_(1)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-bas-dr_(1)" position={[0, 0.196, -1.098]} rotation={[-0.018, 0, 0]}>
              <mesh name="avion_DEF5aileron-AV-bas-dr_(1)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-bas-dr_(1)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-haut-ga_(1)">
              <mesh name="avion_DEF5aileron-AV-haut-ga_(1)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-haut-ga_(1)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5Layer11_(1)">
              <mesh name="avion_DEF5Layer11_(1)_AVION_0" geometry={nodes['avion_DEF5Layer11_(1)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <mesh name="avion_DEF5corps_(1)_AVION_0" geometry={nodes['avion_DEF5corps_(1)_AVION_0'].geometry} material={materials.AVION} />
            <mesh name="avion_DEF5corps_(1)_VERRE_0" geometry={nodes['avion_DEF5corps_(1)_VERRE_0'].geometry} material={materials.VERRE} />
            <mesh name="avion_DEF5corps_(1)_PERSOS_0" geometry={nodes['avion_DEF5corps_(1)_PERSOS_0'].geometry} material={materials.PERSOS} />
          </group>
        </group>
        <group name="TOT_(2)" position={[2000, 0, 0]}>
          <group name="avion_DEF5corps_(2)" rotation={[-0.009, -0.023, -0.004]}>
            <group name="avion_DEF5elice_(2)" rotation={[0, 0, -2.013]}>
              <mesh name="avion_DEF5elice_(2)_fer_elices2_0" geometry={nodes['avion_DEF5elice_(2)_fer_elices2_0'].geometry} material={materials.fer_elices2} />
              <mesh name="avion_DEF5elice_(2)_black_0" geometry={nodes['avion_DEF5elice_(2)_black_0'].geometry} material={materials.black} />
            </group>
            <group name="avion_DEF5aileron-AR-vert_(2)" rotation={[0.021, 0.046, 0]}>
              <mesh name="avion_DEF5aileron-AR-vert_(2)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-vert_(2)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AR-ga_(2)" position={[0.071, -22.992, 1.292]} rotation={[-0.027, 0.046, 0.002]}>
              <mesh name="avion_DEF5aileron-AR-ga_(2)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-ga_(2)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AR-dr_(2)" position={[0.02, -8.531, 0.352]} rotation={[0.003, 0.046, 0]}>
              <mesh name="avion_DEF5aileron-AR-dr_(2)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-dr_(2)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-bas-ga_(2)" position={[-0.137, 0.547, -2.951]} rotation={[-0.027, 0.046, 0.002]}>
              <mesh name="avion_DEF5aileron-AV-bas-ga_(2)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-bas-ga_(2)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-bas-dr_(2)" position={[-0.051, 0.219, -1.093]} rotation={[0.003, 0.046, 0]}>
              <mesh name="avion_DEF5aileron-AV-bas-dr_(2)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-bas-dr_(2)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-haut-ga_(2)" rotation={[0.021, 0.046, 0]}>
              <mesh name="avion_DEF5aileron-AV-haut-ga_(2)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-haut-ga_(2)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5Layer11_(2)">
              <mesh name="avion_DEF5Layer11_(2)_AVION_0" geometry={nodes['avion_DEF5Layer11_(2)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <mesh name="avion_DEF5corps_(2)_AVION_0" geometry={nodes['avion_DEF5corps_(2)_AVION_0'].geometry} material={materials.AVION} />
            <mesh name="avion_DEF5corps_(2)_VERRE_0" geometry={nodes['avion_DEF5corps_(2)_VERRE_0'].geometry} material={materials.VERRE} />
            <mesh name="avion_DEF5corps_(2)_PERSOS_0" geometry={nodes['avion_DEF5corps_(2)_PERSOS_0'].geometry} material={materials.PERSOS} />
          </group>
        </group>
        <group name="TOT_(3)" position={[-2000, 0, 0]}>
          <group name="avion_DEF5corps_(3)" rotation={[0.006, 0.006, -0.006]}>
            <group name="avion_DEF5elice_(3)" rotation={[0, 0, 2.5]}>
              <mesh name="avion_DEF5elice_(3)_fer_elices2_0" geometry={nodes['avion_DEF5elice_(3)_fer_elices2_0'].geometry} material={materials.fer_elices2} />
              <mesh name="avion_DEF5elice_(3)_black_0" geometry={nodes['avion_DEF5elice_(3)_black_0'].geometry} material={materials.black} />
            </group>
            <group name="avion_DEF5aileron-AR-vert_(3)">
              <mesh name="avion_DEF5aileron-AR-vert_(3)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-vert_(3)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AR-ga_(3)" position={[0, -22.96, 1.776]} rotation={[-0.048, 0, 0]}>
              <mesh name="avion_DEF5aileron-AR-ga_(3)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-ga_(3)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AR-dr_(3)" position={[0, -8.521, 0.531]} rotation={[-0.018, 0, 0]}>
              <mesh name="avion_DEF5aileron-AR-dr_(3)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-dr_(3)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-bas-ga_(3)" position={[0, 0.485, -2.965]} rotation={[-0.048, 0, 0]}>
              <mesh name="avion_DEF5aileron-AV-bas-ga_(3)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-bas-ga_(3)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-bas-dr_(3)" position={[0, 0.196, -1.098]} rotation={[-0.018, 0, 0]}>
              <mesh name="avion_DEF5aileron-AV-bas-dr_(3)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-bas-dr_(3)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-haut-ga_(3)">
              <mesh name="avion_DEF5aileron-AV-haut-ga_(3)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-haut-ga_(3)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5Layer11_(3)">
              <mesh name="avion_DEF5Layer11_(3)_AVION_0" geometry={nodes['avion_DEF5Layer11_(3)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <mesh name="avion_DEF5corps_(3)_AVION_0" geometry={nodes['avion_DEF5corps_(3)_AVION_0'].geometry} material={materials.AVION} />
            <mesh name="avion_DEF5corps_(3)_VERRE_0" geometry={nodes['avion_DEF5corps_(3)_VERRE_0'].geometry} material={materials.VERRE} />
            <mesh name="avion_DEF5corps_(3)_PERSOS_0" geometry={nodes['avion_DEF5corps_(3)_PERSOS_0'].geometry} material={materials.PERSOS} />
          </group>
        </group>
        <group name="TOT_(4)" position={[1000, 1000, 0]}>
          <group name="avion_DEF5corps_(4)" position={[0.028, 0.028, -0.028]} rotation={[-0.027, -0.017, -0.015]}>
            <group name="avion_DEF5elice_(4)" rotation={[0, 0, 2.766]}>
              <mesh name="avion_DEF5elice_(4)_fer_elices2_0" geometry={nodes['avion_DEF5elice_(4)_fer_elices2_0'].geometry} material={materials.fer_elices2} />
              <mesh name="avion_DEF5elice_(4)_black_0" geometry={nodes['avion_DEF5elice_(4)_black_0'].geometry} material={materials.black} />
            </group>
            <group name="avion_DEF5aileron-AR-vert_(4)">
              <mesh name="avion_DEF5aileron-AR-vert_(4)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-vert_(4)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AR-ga_(4)" position={[0, -22.96, 1.776]} rotation={[-0.048, 0, 0]}>
              <mesh name="avion_DEF5aileron-AR-ga_(4)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-ga_(4)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AR-dr_(4)" position={[0, -8.521, 0.531]} rotation={[-0.018, 0, 0]}>
              <mesh name="avion_DEF5aileron-AR-dr_(4)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-dr_(4)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-bas-ga_(4)" position={[0, 0.485, -2.965]} rotation={[-0.048, 0, 0]}>
              <mesh name="avion_DEF5aileron-AV-bas-ga_(4)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-bas-ga_(4)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-bas-dr_(4)" position={[0, 0.196, -1.098]} rotation={[-0.018, 0, 0]}>
              <mesh name="avion_DEF5aileron-AV-bas-dr_(4)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-bas-dr_(4)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-haut-ga_(4)">
              <mesh name="avion_DEF5aileron-AV-haut-ga_(4)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-haut-ga_(4)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5Layer11_(4)">
              <mesh name="avion_DEF5Layer11_(4)_AVION_0" geometry={nodes['avion_DEF5Layer11_(4)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <mesh name="avion_DEF5corps_(4)_AVION_0" geometry={nodes['avion_DEF5corps_(4)_AVION_0'].geometry} material={materials.AVION} />
            <mesh name="avion_DEF5corps_(4)_VERRE_0" geometry={nodes['avion_DEF5corps_(4)_VERRE_0'].geometry} material={materials.VERRE} />
            <mesh name="avion_DEF5corps_(4)_PERSOS_0" geometry={nodes['avion_DEF5corps_(4)_PERSOS_0'].geometry} material={materials.PERSOS} />
          </group>
        </group>
        <group name="TOT_(5)" position={[-1000, 1000, 0]}>
          <group name="avion_DEF5corps_(5)" position={[0.142, 0.142, -0.142]} rotation={[-0.001, -0.001, 0.001]}>
            <group name="avion_DEF5elice_(5)" rotation={[0, 0, -2.505]}>
              <mesh name="avion_DEF5elice_(5)_fer_elices2_0" geometry={nodes['avion_DEF5elice_(5)_fer_elices2_0'].geometry} material={materials.fer_elices2} />
              <mesh name="avion_DEF5elice_(5)_black_0" geometry={nodes['avion_DEF5elice_(5)_black_0'].geometry} material={materials.black} />
            </group>
            <group name="avion_DEF5aileron-AR-vert_(5)">
              <mesh name="avion_DEF5aileron-AR-vert_(5)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-vert_(5)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AR-ga_(5)" position={[0, -22.96, 1.776]} rotation={[-0.048, 0, 0]}>
              <mesh name="avion_DEF5aileron-AR-ga_(5)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-ga_(5)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AR-dr_(5)" position={[0, -8.521, 0.531]} rotation={[-0.018, 0, 0]}>
              <mesh name="avion_DEF5aileron-AR-dr_(5)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-dr_(5)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-bas-ga_(5)" position={[0, 0.485, -2.965]} rotation={[-0.048, 0, 0]}>
              <mesh name="avion_DEF5aileron-AV-bas-ga_(5)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-bas-ga_(5)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-bas-dr_(5)" position={[0, 0.196, -1.098]} rotation={[-0.018, 0, 0]}>
              <mesh name="avion_DEF5aileron-AV-bas-dr_(5)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-bas-dr_(5)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-haut-ga_(5)">
              <mesh name="avion_DEF5aileron-AV-haut-ga_(5)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-haut-ga_(5)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5Layer11_(5)">
              <mesh name="avion_DEF5Layer11_(5)_AVION_0" geometry={nodes['avion_DEF5Layer11_(5)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <mesh name="avion_DEF5corps_(5)_AVION_0" geometry={nodes['avion_DEF5corps_(5)_AVION_0'].geometry} material={materials.AVION} />
            <mesh name="avion_DEF5corps_(5)_VERRE_0" geometry={nodes['avion_DEF5corps_(5)_VERRE_0'].geometry} material={materials.VERRE} />
            <mesh name="avion_DEF5corps_(5)_PERSOS_0" geometry={nodes['avion_DEF5corps_(5)_PERSOS_0'].geometry} material={materials.PERSOS} />
          </group>
        </group>
        <group name="TOT_(6)" position={[1000, -1000, 0]}>
          <group name="avion_DEF5corps_(6)" position={[0.028, 0.028, -0.028]} rotation={[-0.03, 0.046, 0.027]}>
            <group name="avion_DEF5elice_(6)" rotation={[0, 0, 1.102]}>
              <mesh name="avion_DEF5elice_(6)_fer_elices2_0" geometry={nodes['avion_DEF5elice_(6)_fer_elices2_0'].geometry} material={materials.fer_elices2} />
              <mesh name="avion_DEF5elice_(6)_black_0" geometry={nodes['avion_DEF5elice_(6)_black_0'].geometry} material={materials.black} />
            </group>
            <group name="avion_DEF5aileron-AR-vert_(6)">
              <mesh name="avion_DEF5aileron-AR-vert_(6)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-vert_(6)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AR-ga_(6)" position={[0, 21.94, -0.674]} rotation={[0.045, 0, 0]}>
              <mesh name="avion_DEF5aileron-AR-ga_(6)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-ga_(6)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AR-dr_(6)" position={[0, 21.931, -0.675]} rotation={[0.045, 0, 0]}>
              <mesh name="avion_DEF5aileron-AR-dr_(6)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-dr_(6)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-bas-ga_(6)" position={[0, -0.593, 2.801]} rotation={[0.045, 0, 0]}>
              <mesh name="avion_DEF5aileron-AV-bas-ga_(6)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-bas-ga_(6)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-bas-dr_(6)" position={[0, -0.592, 2.805]} rotation={[0.045, 0, 0]}>
              <mesh name="avion_DEF5aileron-AV-bas-dr_(6)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-bas-dr_(6)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-haut-ga_(6)" position={[1.333, 0.57, -1.695]}>
              <mesh name="avion_DEF5aileron-AV-haut-ga_(6)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-haut-ga_(6)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5Layer11_(6)">
              <mesh name="avion_DEF5Layer11_(6)_AVION_0" geometry={nodes['avion_DEF5Layer11_(6)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <mesh name="avion_DEF5corps_(6)_AVION_0" geometry={nodes['avion_DEF5corps_(6)_AVION_0'].geometry} material={materials.AVION} />
            <mesh name="avion_DEF5corps_(6)_VERRE_0" geometry={nodes['avion_DEF5corps_(6)_VERRE_0'].geometry} material={materials.VERRE} />
            <mesh name="avion_DEF5corps_(6)_PERSOS_0" geometry={nodes['avion_DEF5corps_(6)_PERSOS_0'].geometry} material={materials.PERSOS} />
          </group>
        </group>
        <group name="TOT_(7)" position={[-1000.478, -1000, 0.148]}>
          <group name="avion_DEF5corps_(7)" position={[0.144, 0.144, -0.144]} rotation={[-0.001, -0.001, 0.001]}>
            <group name="avion_DEF5elice_(7)" rotation={[0, 0, 0.945]}>
              <mesh name="avion_DEF5elice_(7)_fer_elices2_0" geometry={nodes['avion_DEF5elice_(7)_fer_elices2_0'].geometry} material={materials.fer_elices2} />
              <mesh name="avion_DEF5elice_(7)_black_0" geometry={nodes['avion_DEF5elice_(7)_black_0'].geometry} material={materials.black} />
            </group>
            <group name="avion_DEF5aileron-AR-vert_(7)">
              <mesh name="avion_DEF5aileron-AR-vert_(7)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-vert_(7)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AR-ga_(7)" position={[0, -22.96, 1.776]} rotation={[-0.048, 0, 0]}>
              <mesh name="avion_DEF5aileron-AR-ga_(7)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-ga_(7)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AR-dr_(7)" position={[0, -8.521, 0.531]} rotation={[-0.018, 0, 0]}>
              <mesh name="avion_DEF5aileron-AR-dr_(7)_AVION_0" geometry={nodes['avion_DEF5aileron-AR-dr_(7)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-bas-ga_(7)" position={[0, 0.485, -2.965]} rotation={[-0.048, 0, 0]}>
              <mesh name="avion_DEF5aileron-AV-bas-ga_(7)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-bas-ga_(7)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-bas-dr_(7)" position={[0, 0.196, -1.098]} rotation={[-0.018, 0, 0]}>
              <mesh name="avion_DEF5aileron-AV-bas-dr_(7)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-bas-dr_(7)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5aileron-AV-haut-ga_(7)">
              <mesh name="avion_DEF5aileron-AV-haut-ga_(7)_AVION_0" geometry={nodes['avion_DEF5aileron-AV-haut-ga_(7)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <group name="avion_DEF5Layer11_(7)">
              <mesh name="avion_DEF5Layer11_(7)_AVION_0" geometry={nodes['avion_DEF5Layer11_(7)_AVION_0'].geometry} material={materials.AVION} />
            </group>
            <mesh name="avion_DEF5corps_(7)_AVION_0" geometry={nodes['avion_DEF5corps_(7)_AVION_0'].geometry} material={materials.AVION} />
            <mesh name="avion_DEF5corps_(7)_VERRE_0" geometry={nodes['avion_DEF5corps_(7)_VERRE_0'].geometry} material={materials.VERRE} />
            <mesh name="avion_DEF5corps_(7)_PERSOS_0" geometry={nodes['avion_DEF5corps_(7)_PERSOS_0'].geometry} material={materials.PERSOS} />
          </group>
        </group>
      </group>
    </group>
  );
});

export default Tr;
useGLTF.preload("/models/tr-transformed.glb");

