/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf --transform 
Files: scene.gltf [52.01KB] > C:\Users\ProUSer\Documents\3d\More\massey_ferguson_1525_tractor\scene-transformed.glb [6.02MB] (-11469%)
Author: johnnokomis (https://sketchfab.com/johnnokomis)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/massey-ferguson-1525-tractor-5f62b3d9838b495f94294dc34cac8cc5
Title: Massey Ferguson 1525 Tractor
*/
"use client"
import React, { useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

const Tractor = React.memo(function Tractor(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/tractor-transformed.glb");

  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.position.y =
      -1.0 + Math.sin(state.clock.elapsedTime) * 0.30;
    modelRef.current.rotation.y += 0.1;
  });
  return (
    <group 
    {...props}
      dispose={null}
      ref={modelRef}
      position={[0, -1.5, 0]}
      scale={[0.06, 0.06, 0.06]}
      rotation={[0.25, 0, 0]}
    >
    <mesh 
      geometry={nodes.Model_material0_0.geometry} 
      material={materials.material0} 
      rotation={[2.148, 0.36, 0.485]} />
    </group>
  );

});

export default Tractor;
useGLTF.preload("/models/tractor-transformed.glb");


