/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf --transform 
Files: scene.gltf [302.32KB] > C:\Users\ProUSer\Documents\3d\More\construction_truck\scene-transformed.glb [1.24MB] (-312%)
Author: Montassar-f (https://sketchfab.com/Montassar-f)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/construction-truck-c573303be1f04e0c94cfa245c2f2ddcf
Title: Construction truck
*/


"use client"
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';


const Truck = React.memo(function Truck (props) {
  const { nodes, materials } = useGLTF('/models/truck-transformed.glb')
  const modelRef= useRef();
  useFrame((state) => {
    /*modelRef.current.position.y =
      -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;*/
    modelRef.current.rotation.y += 0.05;
  });


  return (
    <group
     {...props} dispose={null}
     ref={modelRef}
      position={[0, 0, 0]}
      scale={[0.3, 0.3, 0.3]}
      rotation={[0.25, 0, 0]}
     
     >
      <mesh geometry={nodes.pCylinder58_lambert1_0.geometry} material={materials.PaletteMaterial001} position={[0, 0.061, 0]} rotation={[0, 0, -Math.PI]} scale={[-5.795, 0.09, 5.795]} />
      <mesh geometry={nodes.pCylinder1_tire_metal_0.geometry} material={materials.tire_metal} position={[1.141, 2.322, -0.119]} scale={[0.067, 0.094, 0.067]} />
      <mesh geometry={nodes.wire9_cable_0.geometry} material={materials.cable} position={[1.298, 0.774, 0.509]} rotation={[-0.069, 0.053, 0.133]} scale={[0.336, 0.336, 0.34]} />
      <mesh geometry={nodes.pCylinder74_base_material_yellow_0.geometry} material={materials.base_material_yellow} position={[1.222, 2.507, 1.379]} rotation={[-0.148, 0, 0]} scale={[0.017, 0.053, 0.017]} />
      <mesh geometry={nodes.pCylinder64_LAMP_0.geometry} material={materials.LAMP} position={[0.641, 2.045, 1.047]} rotation={[-0.543, 0.039, -0.042]} scale={0.023} />
      <mesh geometry={nodes.pSphere2_finger_metal_0.geometry} material={materials.finger_metal} position={[0.647, 2.22, 1.066]} scale={0.022} />
      <mesh geometry={nodes.pCylinder63_chrome_0.geometry} material={materials.PaletteMaterial002} position={[0.494, 2.126, 1.072]} rotation={[-0.948, 0, 0]} scale={[0.009, 0.073, 0.009]} />
      <mesh geometry={nodes.pCube67_base_metal__2_0.geometry} material={materials.base_metal__2} scale={0.534} />
      <mesh geometry={nodes.pCylinder27_cabine_metal_0.geometry} material={materials.cabine_metal} position={[0, 1.01, 0]} scale={0.534} />
      <mesh geometry={nodes.polySurface84_tire_metal_2_0.geometry} material={materials.tire_metal_2} position={[0, 1.01, 0]} scale={0.534} />
      <mesh geometry={nodes.pCube7_new_hand_1_texture_0.geometry} material={materials.new_hand_1_texture} position={[0, 1.01, 0]} scale={0.534} />
      <mesh geometry={nodes.pCube8_hand_2_new_0.geometry} material={materials.hand_2_new} position={[-0.194, 2.349, 4.084]} rotation={[-0.218, 0, 0]} scale={[0.445, 0.54, 0.44]} />
      <mesh geometry={nodes.pCube2_glasse_0.geometry} material={materials.PaletteMaterial003} position={[0.69, 2.1, 0.876]} scale={[1.03, 1.876, 0.958]} />
      <instancedMesh args={[nodes.pCylinder69_GREEN_0.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.pCylinder69_GREEN_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCylinder57_tire_metal_0.geometry, materials.tire_metal, 8]} instanceMatrix={nodes.pCylinder57_tire_metal_0.instanceMatrix} />
    </group>
  );
});

export default Truck;
useGLTF.preload('/models/truck-transformed.glb')
