/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [8.69KB] > C:\Users\ProUSer\Documents\3d\voxel_web_development\scene-transformed.glb [8.84KB] (-2%)
Author: Diego G. (https://sketchfab.com/empty_mirror)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/voxel-web-development-50ad959d6c6b4799806c45bfa46ca550
Title: Voxel Web Development
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const WDModel= React.memo(function Model(props) {
  const { nodes, materials} = useGLTF('/models/wd-transformed.glb')
  const modelRef = useRef();

  useFrame( ()=> {
      
    modelRef.current.rotation.y+=0.1;
    

  });

  return (
    <group
     {...props} 
     ref={modelRef}
     dispose={null}
     position={[0,0.5,0]}
     rotation={[0.25,0,0]}
     scale={[0.3,0.3,0.3]}
     >
      <mesh geometry={nodes.Object_4.geometry} material={materials.palette} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['palette.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['palette.002']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  );
});
export default WDModel;
useGLTF.preload('/models/wd-transformed.glb')
